### ISSUE TITLE
Cannot install package

### ISSUE THREAD

**Issue by peterbandi** [smatsumoto78/pyzorder#1]
The installation of the pyzorder package with `pip install pyzorder` command fails with the following error:
```
ValueError: Only strings are accepted for the license_file field, files are not accepted
```

I think it is because including files with the `file:` directive for the `long_description` field in the **setup.cfg** is no logner supported by **setuptools**.

python 3.9
setuptools 58.0.4

**Comment by smatsumt** [comment]
@peterbandi 
Thanks for letting me know! And sorry for late reply.

I've fixed the issue with recreating the pyzorder package. 

Now, new package 0.0.2 is released. I confirmed package can be installed with Python3.9.2, pip 22.0.4, setuptools 62.1.0.

If you have any trouble, please re-open the issue and let me know.
